/* tslint:disable:only-arrow-functions */
import {FormatStackTrace} from "../src";

describe('helpers', function () {
    it('formats stack trace', function () {
        const stackSample = 'Error: error object    at extractParametersFromArguments (/Users/roberto/dev/console-log-json/src/logger.ts:455:21)    at /Users/roberto/dev/console-log-json/src/logger.ts:337:40    at new Promise (<anonymous>)    at logUsingWinston (/Users/roberto/dev/console-log-json/src/logger.ts:328:22)    at Object.LoggerAdaptToConsole.console.error (/Users/roberto/dev/console-log-json/src/logger.ts:234:10)    at Context.<anonymous> (/Users/roberto/dev/console-log-json/test/logger.test.ts:18:21)    at callFn (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runnable.js:387:21)    at Test.Runnable.run (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runnable.js:379:7)    at Runner.runTest (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:535:10)    at /Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:653:12    at next (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:447:14)    at /Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:457:7    at next (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:362:14)    at Immediate._onImmediate (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:425:5)    at processImmediate (internal/timers.js:439:21)Caused By: Error: error object    at Context.<anonymous> (/Users/roberto/dev/console-log-json/test/logger.test.ts:18:42)    at callFn (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runnable.js:387:21)    at Test.Runnable.run (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runnable.js:379:7)    at Runner.runTest (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:535:10)    at /Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:653:12    at next (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:447:14)    at /Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:457:7    at next (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:362:14)    at Immediate._onImmediate (/Users/roberto/dev/console-log-json/node_modules/mocha/lib/runner.js:425:5)    at processImmediate (internal/timers.js:439:21)';
        const result = FormatStackTrace.toNewLines(stackSample);

        console.log(result);
    })
});